name: CI
on: 
  push:
    branches: 
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "This is the building process"

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: echo "It test the product that is build"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
     # - uses: actions/checkout@v4
      - name: Deploy
        run:  echo "Deploying the code successfully"
    
          

  
